baseURL: /
languageCode: ru-ru
build:
  writeStats: true
title: aafu theme
theme: aafu

params:
  author: Darshan Baral
  description: Website title
  copyright: powered by [hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  accordion:
    - item: about_me
      expand: true # only the first `expand: true` will take effect
    - item: education
    - item: hobbies
